-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 12:04:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema checkpoint4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `checkpoint4` ;

-- -----------------------------------------------------
-- Schema checkpoint4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkpoint4` DEFAULT CHARACTER SET utf8 ;
USE `checkpoint4` ;

-- -----------------------------------------------------
-- Table `checkpoint4`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint4`.`user` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `checkpoint4`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint4`.`language` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `source_logo` VARCHAR(1000) NOT NULL,
  `name_logo` VARCHAR(150) NOT NULL,
  `user_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `user_Id`),
  INDEX `fk_language_user_idx` (`user_Id` ASC) VISIBLE,
  CONSTRAINT `fk_language_user`
    FOREIGN KEY (`user_Id`)
    REFERENCES `checkpoint4`.`user` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `checkpoint4`.`dev_tool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint4`.`dev_tool` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `source_logo` VARCHAR(1000) NOT NULL,
  `name_logo` VARCHAR(150) NOT NULL,
  `user_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `user_Id`),
  INDEX `fk_dev_tool_user1_idx` (`user_Id` ASC) VISIBLE,
  CONSTRAINT `fk_dev_tool_user1`
    FOREIGN KEY (`user_Id`)
    REFERENCES `checkpoint4`.`user` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `checkpoint4`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint4`.`project` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `source_image` VARCHAR(1000) NOT NULL,
  `name_image` VARCHAR(150) NOT NULL,
  `source` VARCHAR(1000) NOT NULL,
  `abstract` VARCHAR(2000) NOT NULL,
  `client_name` VARCHAR(100) NOT NULL,
  `user_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `user_Id`),
  INDEX `fk_project_user1_idx` (`user_Id` ASC) VISIBLE,
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`user_Id`)
    REFERENCES `checkpoint4`.`user` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `user` (`email`,`password`) VALUES ('nantua@marcos.com','12345');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
